### PR TITLE
Change temp view name to uppercase, fix various build issues

### PR DESCRIPTION
**Pull request by goodwanghan**

### CODE REVIEW

**Review by kvnkho — APPROVED** [review]

**Comment by cristianmatache** [comment]
@goodwanghan when will this change be released? at least as a dev version

**Comment by goodwanghan** [comment]
> @goodwanghan when will this change be released? at least as a dev version

I can release a dev version today. The 0.9.0 version will be released tomorrow.

**Comment by cristianmatache** [comment]
no rush if the actual release comes tomorrow, I am temporarily pointing to the latest commit on `master` in my requirements.txt
thank you

**Comment by goodwanghan** [comment]
> @goodwanghan when will this change be released? at least as a dev version

I released 0.9.0.dev4

Tomorrow morning, 0.9.0 will be released

Could I know how you are using Fugue? With what backend?

**Pull request merged**
